# pve cloud custom definitions

# will trigger kubespray caching mechanism as soon as the mirror vm is deployed
# download_run_once and download_localhost kubespray cache control vars are set in sync_kubespray playbook
download_cache_dir: "{{ lookup('env', 'HOME') }}/.cache/kubespray"

# use docker on localhost and containerd on nodes, need to set both vars for it to work ...?
container_manager_on_localhost: "docker"
image_command_tool_on_localhost: "docker"
