---
# tasks file for bdd_server_tls_certs

- name: generate ca private key
  community.crypto.openssl_privatekey_pipe:
    type: "Ed25519"
  register: ca_privatekey

- name: generate ca csr
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ ca_privatekey.privatekey }}"
    common_name: "PXC Backup CA"
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: generate self-signed ca certificate
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ ca_csr.csr }}"
    privatekey_content: "{{ ca_privatekey.privatekey }}"
    provider: selfsigned
    selfsigned_not_after: "+3650d"
  register: ca_cert

- name: generate server private key
  community.crypto.openssl_privatekey_pipe:
    type: "Ed25519"
  register: server_privatekey

- name: generate server csr
  community.crypto.openssl_csr_pipe:
    privatekey_content: "{{ server_privatekey.privatekey }}"
    common_name: "bdd.{{ pve_cloud_domain }}"
    use_common_name_for_san: false
    subject_alt_name:
      - "DNS:bdd.{{ pve_cloud_domain }}"
      - "DNS:*.{{ pve_cloud_domain }}"
      - "IP:127.0.0.1"
      - "IP:::1"
  register: server_csr

- name: sign server certificate with ca
  community.crypto.x509_certificate_pipe:
    csr_content: "{{ server_csr.csr }}"
    provider: ownca
    ownca_content: "{{ ca_cert.certificate }}"
    ownca_privatekey_content: "{{ ca_privatekey.privatekey }}"
    ownca_not_after: "+3650d"
  register: server_cert

- name: compile tls secrets row
  set_fact:
    bdd_tls_row:
      cloud_domain: "{{ pve_cloud_domain }}"
      secret_name: "{{ stack_name }}-bdd-tls-certs"
      secret_data:
        ca_cert.crt: "{{ ca_cert.certificate }}"
        ca_private_key.key: "{{ ca_privatekey.privatekey }}"
        server_cert.crt: "{{ server_cert.certificate }}"
        server_private_key.key: "{{ server_privatekey.privatekey }}"

- name: delete existing bdd-tls-certs from postgres
  alchemy_delete:
    pg_conn_str: "{{ pg_conn_str }}"
    table: px_cloud_secrets
    where:
      cloud_domain: "{{ pve_cloud_domain }}"
      secret_name: "{{ stack_name }}-bdd-tls-certs"

- name: write bdd-tls-certs to postgres
  alchemy_write:
    pg_conn_str: "{{ pg_conn_str }}"
    table: px_cloud_secrets
    rows:
      - "{{ bdd_tls_row }}"
