---
# tasks file for setup_pxzfs_localpv_zpool

- name: update kernel and headers
  become: true
  ansible.builtin.apt:
    update_cache: true
    name:
      - "linux-image-{{ arch_mapping[ansible_architecture] }}"
      - "linux-headers-{{ arch_mapping[ansible_architecture] }}"
    state: latest
  register: kernel_update

- name: reboot after kernel update
  become: true
  ansible.builtin.reboot:
    msg: "Rebooting after kernel update"
    reboot_timeout: 900
  when: kernel_update.changed

- name: install zfs
  become: true
  ansible.builtin.apt:
    name:
      - zfs-dkms
      - zfsutils-linux
    state: present
  register: zfs_install

- name: dkms autoconf
  become: true
  ansible.builtin.command:
    cmd: dkms autoinstall
  when: zfs_install.changed

- name: load zfs module
  become: true
  community.general.modprobe:
    name: zfs
    state: present

- name: create csi zpool
  become: true
  # experimental fork of community.general.zpool with fixxed for /dev/disk/by-id definition
  # of disks
  pxc.cloud.zpool:
    name: tank-pv
    vdevs: "{{ zpool_vdevs }}"
    pool_properties: "{{ zpool_properties }}"
    force: "{{ zpool_create_force }}"
