---
# tasks file for ssh_enforce_key_auth
# this still allows for Match User ... to enable targeted password auth
- name: Disable top level ssh password authentication
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication\s+yes'
    line: 'PasswordAuthentication no'
    state: present
  register: ssh_key_auth_change

- name: Restart sshd
  become: true
  service:
    name: sshd
    state: restarted
  when: ssh_key_auth_change.changed
