- name: Sync nodes
  hosts: localhost
  tasks:
    - name: Get blakes
      pxc.cloud.blakes_for_inv:
        vms: "{{ lxcs | default(qemus) }}"
        stack_name: ""
      register: result
      run_once: true

    - debug:
        var: result.blakes
      run_once: true