- name: Migrate blakes (pre stack_name include to include)
  hosts: target_pve
  tasks:
    - name: Get old blakes
      pxc.cloud.blakes_for_inv:
        vms: "{{ lxcs | default(qemus) }}"
        stack_name: ""
      register: old_blakes
      run_once: true

    - name: Get new blakes lxcs
      pxc.cloud.blakes_for_inv:
        vms: "{{ lxcs | default(qemus) }}"
        stack_name: "{{ stack_name }}"
      register: new_blakes
      run_once: true

    - debug:
        msg: "{{ new_blakes.blakes | map('first') }}"
      run_once: true

    - set_fact:
        old_new_map: "{{ dict((old_blakes.blakes | map('first')) | zip((new_blakes.blakes | map('first')))) }}"

    - debug:
        var: old_new_map
      run_once: true

    # get existing vms
    - name: Get existing vms
      command: pvesh get /cluster/resources --type vm --output-format json
      register: pve_vms
      run_once: true

    - set_fact:
        stack_vms: "{{ pve_vms.stdout | from_json |  selectattr('tags', 'defined') | selectattr('tags', 'search', stack_name + '.' + pve_cloud_domain) | list }}"
      run_once: true

    - set_fact:
        override_values: "{{ (stack_vms | map(attribute='vmid') | list) | zip(stack_vms | map(attribute='tags') | list) | zip(stack_vms | map(attribute='node') | list) }}"

    - debug:
        var: override_values
      run_once: true

    - set_fact:
        blakes: "{{ stack_vms | map(attribute='tags') | map('split', ';') | map('select', 'search', '-blake$') | map('first') | list }}"

    - debug:
        var: blakes
      run_once: true

    - set_fact:
        old_vms_zipped: "{{ blakes | zip(override_values) }}"
      run_once: true

    - debug:
        var: old_vms_zipped
      run_once: true

    - name: update lxc tags
      command: "pct set {{ item.1.0.0 }} --tags '{{ item.1.0.1 | replace(item.0, old_new_map[item.0]) }}'"
      loop: "{{ old_vms_zipped }}"
      when: lxcs is defined and inventory_hostname == item.1.1 + "." + pve_cluster

    - name: update qemu tags
      command: "qm set {{ item.1.0.0 }} --tags '{{ item.1.0.1 | replace(item.0, old_new_map[item.0]) }}'"
      loop: "{{ old_vms_zipped }}"
      when: qemus is defined and inventory_hostname == item.1.1 + "." + pve_cluster

