- name: Slurp certificates from pve
  hosts: target_pve
  roles:
    - slurp_cluster_secrets

- name: Fetch ha-postgres
  hosts: postgres_stack

- name: Setup haproxy
  hosts: lxcs
  roles:
    - parse_cluster_secrets
  tasks:
    - name: Check if floating ips are defined
      fail:
        msg: "ERROR: 'pve_haproxy_floating_ip_external' or 'pve_haproxy_floating_ip_internal' is not in pve cloud vars!"
      when: pve_haproxy_floating_ip_external is not defined or pve_haproxy_floating_ip_internal is not defined

    - name: Install keepalived
      ansible.builtin.apt:
        update_cache: yes
        name: keepalived
        state: present

    - name: install haproxy
      ansible.builtin.apt:
        name: haproxY
        state: present

    - name: enable and start proxy
      ansible.builtin.service:
        name: haproxy
        state: started
        enabled: yes

    - name: Enable binding to keepalived vrips
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: '1'
        state: present
        sysctl_set: yes
        reload: yes

    - name: check if postgres is available
      delegate_to: pxc-executor-host
      community.postgresql.postgres_ping:
        host: "{{ pve_haproxy_floating_ip_internal }}"
        port: 5000
        login_db: postgres
        login_user: postgres
        login_password: "{{ postgres_password  }}" 
      register: postgres_connection_check
      ignore_errors: true

    - set_fact:
        proxy_stack_fqdn: "{{ stack_name }}.{{ pve_cloud_domain }}"

    - name: Try fetch config from postgres (on consecutive applies)
      include_role:
        name: select_haproxy_conf
      when: postgres_connection_check.is_available

    - include_role:
        name: apply_haproxy_conf

    - name: Get vrid from stack_name
      set_fact:
        vrid: "{{ (( stack_name | hash('sha256') | int(base=16)) % 254) + 1 }}"
        vrid_int: "{{ (( stack_name | hash('sha256') | int(base=16)) % 254) + 2 }}"

    - name: copy keeaplived conf
      ansible.builtin.copy:
        dest: /etc/keepalived/keepalived.conf
        content: |
          # vrrp for external ingress haproxy
          vrrp_instance VI_1 {
            state {{ 'MASTER' if keepalived_master else 'BACKUP' }}
            interface eth0
            virtual_router_id {{ vrid }}
            priority {{ '255' if keepalived_master else '254' }}
            advert_int 1
            authentication {
              auth_type PASS
              auth_pass {{ haproxy_keepalived_password }}
            }
            virtual_ipaddress {
              {{ pve_haproxy_floating_ip_external }}/{{ pve_vm_subnet | ansible.utils.ipaddr('prefix') }}
            }
          }
          # internal proxy ip
          vrrp_instance VI_2 {
            state {{ 'MASTER' if keepalived_master else 'BACKUP' }}
            interface eth0
            virtual_router_id {{ vrid_int }}
            priority {{ '255' if keepalived_master else '254' }}
            advert_int 1
            authentication {
              auth_type PASS
              auth_pass {{ haproxy_keepalived_password }}
            }
            virtual_ipaddress {
              {{ pve_haproxy_floating_ip_internal }}/{{ pve_vm_subnet | ansible.utils.ipaddr('prefix') }}
            }
          }

    - name: Restart keepalived
      ansible.builtin.service:
        name: keepalived
        state: restarted
        enabled: yes

    - name: create host record for internal floating ip
      delegate_to: "pxc-executor-host"
      run_once: true
      community.general.nsupdate:
        key_name: "internal."
        key_algorithm: "hmac-sha256"
        key_secret: "{{ bind_internal_key }}"
        server: "{{ bind_master_ip }}"
        zone: "{{ pve_cloud_domain }}"
        record: "internal-{{ stack_name }}"
        value: "{{ pve_haproxy_floating_ip_internal }}"

    - name: create host record for internal floating ip
      delegate_to: "pxc-executor-host"
      run_once: true
      community.general.nsupdate:
        key_name: "internal."
        key_algorithm: "hmac-sha256"
        key_secret: "{{ bind_internal_key }}"
        server: "{{ bind_master_ip }}"
        zone: "{{ pve_cloud_domain }}"
        record: "external-{{ stack_name }}"
        value: "{{ pve_haproxy_floating_ip_external }}"

    - name: create ptr record internal floating ip
      run_once: true
      delegate_to: "pxc-executor-host"
      community.general.nsupdate:
        key_name: "internal."
        key_algorithm: "hmac-sha256"
        key_secret: "{{ bind_internal_key }}"
        server: "{{ bind_master_ip }}"
        zone: "{{ bind_arpa_zone_service_lxcs }}"
        record: "{{ pve_haproxy_floating_ip_internal.split('.')[3] }}"
        type: PTR
        value: "internal-{{ stack_name }}.{{ pve_cloud_domain }}."

    - name: create ptr record external floating ip
      run_once: true
      delegate_to: "pxc-executor-host"
      community.general.nsupdate:
        key_name: "internal."
        key_algorithm: "hmac-sha256"
        key_secret: "{{ bind_internal_key }}"
        server: "{{ bind_master_ip }}"
        zone: "{{ bind_arpa_zone_service_lxcs }}"
        record: "{{ pve_haproxy_floating_ip_external.split('.')[3] }}"
        type: PTR
        value: "external-{{ stack_name }}.{{ pve_cloud_domain }}."
