- name: Slurp screts from pve
  hosts: target_pve
  roles:
    - slurp_cluster_secrets

- name: Install requirements on debian 12 lxc/vm
  hosts: lxcs:qemus
  vars:
    # increment this on releasing a new pve-cloud-backup version
    py_pve_cloud_backup_version: "3.1.0"
  roles:
    - parse_cluster_secrets
    - bdd_server_tls_certs
  tasks:
    - name: install core apt packages
      ansible.builtin.apt:
        name: 
          - python3-venv
          - borgbackup
        state: present
        update_cache: yes
        
    - name: install systemd prom exporter
      include_role:
        name: prometheus.prometheus.systemd_exporter
      when: install_prom_systemd_exporter is defined and install_prom_systemd_exporter

    # install bdd service
    - name: Ensure /opt/bdd directory exists
      ansible.builtin.file:
        path: /opt/bdd
        state: directory

    - name: Ensure /opt/bdd/certs directory exists
      ansible.builtin.file:
        path: /opt/bdd/certs
        state: directory

    - name: Fetch bdd-tls-certs from postgres
      alchemy_read:
        pg_conn_str: "{{ pg_conn_str }}"
        table: px_cloud_secrets
        where:
          cloud_domain: "{{ pve_cloud_domain }}"
          secret_name: "{{ stack_name }}-bdd-tls-certs"
      delegate_to: localhost
      register: fetched_bdd_tls

    - name: Write bdd tls certs to /opt/bdd/certs
      ansible.builtin.copy:
        content: "{{ item.value }}"
        dest: "/opt/bdd/certs/{{ item.key }}"
        mode: '0644'
      loop: "{{ fetched_bdd_tls.query_result[0].secret_data | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Create borg home for backup user
      file:
        path: /srv/backup/borg
        state: directory
        owner: backup
        group: backup
      when: PXC_REMOVABLE_DATASTORES is defined # bdd is running on pbs

    - name: Create Python virtual environment in /opt/bdd/.venv
      ansible.builtin.command:
        cmd: python3 -m venv /opt/bdd/.venv
        creates: /opt/bdd/.venv/bin/activate

    - name: Copy restore instructions
      ansible.builtin.template:
        src: "bdd-RESTORE.md.j2"
        dest: "/opt/bdd/RESTORE.md"

    - name: Install bdd into venv
      ansible.builtin.command:
        cmd: /opt/bdd/.venv/bin/pip install py-pve-cloud-backup=={{ py_pve_cloud_backup_version }}
      when: tdd_local_pypi_host is not defined

    - name: Install bdd into venv from tdd dog local pypi
      ansible.builtin.command:
        cmd: /opt/bdd/.venv/bin/pip install --index-url http://{{ tdd_local_pypi_host }}:8088/simple --trusted-host {{ tdd_local_pypi_host }} py-pve-cloud-backup=={{ py_pve_cloud_backup_version }}
      when: tdd_local_pypi_host is defined

    - name: Create a systemd service file
      template:
        dest: "/etc/systemd/system/bdd.service"
        src: ./bdd.service.j2

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable and start the application service
      systemd:
        name: "bdd"
        state: restarted
        enabled: yes

    # install cron cleanup / check jobs
    - name: copy script
      copy:
        src: bdd-cron.sh
        dest: /opt/bdd/cron.sh
        mode: '0755'

    - name: create bdd cron weekly service
      template:
        dest: "/etc/systemd/system/bdd-cron.service"
        src: ./bdd-cron.service.j2
      vars:
        verify_data: false
    
    - name: create bdd weekly timer
      template:
        dest: "/etc/systemd/system/bdd-cron.timer"
        src: ./bdd-cron.timer.j2
      vars:
        verify_data: false
        # every monday we run basic check + prune
        timer_pattern: "Tue *-*-* 03:00:00"

    - name: create bdd cron monthly service
      template:
        dest: "/etc/systemd/system/bdd-cron-monthly.service"
        src: ./bdd-cron.service.j2
      vars:
        verify_data: true
    
    - name: create bdd monthly timer
      template:
        dest: "/etc/systemd/system/bdd-cron-monthly.timer"
        src: ./bdd-cron.timer.j2
      vars:
        verify_data: true
        # run on the first tuesday of the month
        # this includes borg --verify-data option 
        # which will result in longer runtime
        timer_pattern: "Mon *-*-01..07 03:00:00"

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: enable weekly cron
      systemd:
        name: "bdd-cron.timer"
        state: started
        enabled: yes

    - name: enable monthly cron
      systemd:
        name: "bdd-cron-monthly.timer"
        state: started
        enabled: yes