---
- name: Generic setup
  hosts: all_pve_hosts
  tags:
    - rsync # check version first also for rsync play
  pre_tasks:
    - name: Check if cluster vars exist
      stat:
        path: "/etc/pve/cloud/cluster_vars.yaml"
      register: cvars_stat

    - name: Slurp the file content if it exists
      slurp:
        src: "/etc/pve/cloud/cluster_vars.yaml"
      when: cvars_stat.stat.exists
      register: cvars_slurped

    - name: Set installed cloud collection version
      set_fact:
        existing_cluster_vars: "{{ (cvars_slurped.content | b64decode | from_yaml) }}"
      when: cvars_stat.stat.exists

    - name: Fail when 
      fail:
        msg: "Installed version {{ existing_cluster_vars['pve_cloud_collection_version'] }} is ahead of local version {{ cluster_vars['pve_cloud_collection_version'] }}"
      when: cvars_stat.stat.exists and 'pve_cloud_collection_version' in existing_cluster_vars and existing_cluster_vars['pve_cloud_collection_version'] is version(cluster_vars['pve_cloud_collection_version'], '>', version_type='semver')
    
    # setup pxc venv
    # todo: this should probably be handled by the inventory plugin for cleanliness
    # then we can set interpreter path globally
    - name: install python venv
      apt:
        pkg: 
          - python3-venv
          - skopeo # query mirror registries
        state: present
        update_cache: yes

    - set_fact:
        pip_extra_args: "{{ '--index-url http://' ~ test_repos_ip ~ ':8088/simple --trusted-host ' ~ test_repos_ip if test_repos_ip is defined else '' }}"
      
    - name: create pxc venv
      ansible.builtin.pip:
        name: 
          - "py-pve-cloud=={{ py_pve_cloud_version }}"
          - "aiofiles==25.1.0" # fast slurp
          - "kubernetes==34.1.0" # ansible k8s community
        virtualenv: /root/.pxc-venv
        virtualenv_command: python3 -m venv
        extra_args: "{{ pip_extra_args }}"

    - name: switch to pxc venv
      ansible.builtin.set_fact:
        ansible_python_interpreter: /root/.pxc-venv/bin/python
  
    # install helm cli /kubectl for deploying initial charts
    - name: install check kubectl
      ansible.builtin.stat:
        path: "/usr/local/bin/kubectl"
      register: kubectl_binary

    - name: Download kubectl binary to /usr/local/bin
      ansible.builtin.get_url:
        url: https://dl.k8s.io/release/v1.36.0/bin/linux/{{ arch_mapping[ansible_architecture] }}/kubectl
        dest: /usr/local/bin/kubectl
        mode: '0755'
      when: not kubectl_binary.stat.exists

    - name: install check
      ansible.builtin.stat:
        path: "/usr/local/bin/helm"
      register: helm_binary

    - name: download and extract helm
      ansible.builtin.unarchive:
        src: "https://get.helm.sh/helm-v4.2.0-linux-{{ arch_mapping[ansible_architecture] }}.tar.gz"
        dest: "/tmp"
        remote_src: yes
        creates: "/tmp/linux-{{ arch_mapping[ansible_architecture] }}/helm"
      when: not helm_binary.stat.exists

    - name: move to usr bin folder
      ansible.builtin.copy:
        src: "/tmp/linux-{{ arch_mapping[ansible_architecture] }}/helm"
        dest: "/usr/local/bin/helm"
        mode: '0755'
        remote_src: true
      when: not helm_binary.stat.exists

  vars:
    # for selecting helm version to dl
    arch_mapping:
      x86_64: "amd64"
      aarch64: "arm64"

    # weird logic for the filters, "Units must both match include and not match exclude to be included."
    # include seems to filter some units and not all?
    systemd_exporter_unit_include: '.*\\.service'
    systemd_exporter_unit_exclude: '.*\\.scope'
    smartctl_exporter_system_user: root
    smartctl_exporter_system_group: root
  roles:
    - proxmox_host_avahi
    - prometheus.prometheus.systemd_exporter
    - prometheus.prometheus.smartctl_exporter
  tasks:
    - name: install prometheus-node-exporter
      ansible.builtin.apt:
        name: prometheus-node-exporter
        state: present

    # todo: this should be removed with pve 9 and debian 13 probably
    - name: disable nfsd stat collection (bookworm / newer pve kernels)
      lineinfile:
        path: /etc/default/prometheus-node-exporter
        regexp: '^ARGS='
        line: 'ARGS="--no-collector.nfsd"'
      register: node_exporter_config

    - name: restart node exporter to take effect
      systemd:
        name: prometheus-node-exporter
        state: restarted
      when: node_exporter_config.changed

    # todo: this is currently not idempotent and should consider removal / setting to true
    - name: configure corosync optional votes
      throttle: 1 # consider proxmox shared fs
      ansible.builtin.replace:
        path: /etc/pve/corosync.conf
        regexp: '(name:\s{{ ansible_hostname }}\n\s+nodeid:\s\d+\n\s+quorum_votes:)\s(\d+)'
        replace: '\1 0'
      when: pve_corosync_vote is defined and not pve_corosync_vote

    # install btrfs prometheus exporter for root filesystem
    - include_role:
        name: btrfs_prom_exporter
      when: install_btrfs_root_prom_exporter is defined and install_btrfs_root_prom_exporter

    # log2ram to save disk
    - include_role:
        name: install_log2ram
      when: install_log2ram is defined and install_log2ram

    # download newest lxc templates on hosts
    - name: Update lxc templates
      command: "pveam update"

    # disable openipmi if set
    - name: disable openipmi
      ansible.builtin.systemd:
        name: openipmi
        enabled: no
        state: stopped
        masked: yes
      when: disable_ipmi is defined and disable_ipmi

    # treat zfs scan imports as warnings
    - name: zfs scan error as warn override dir
      when: zfs_scan_error_as_warn is defined and zfs_scan_error_as_warn
      ansible.builtin.file:
        path: /etc/systemd/system/zfs-import-scan.service.d
        state: directory

    - name: zfs scan error as warn override conf
      when: zfs_scan_error_as_warn is defined and zfs_scan_error_as_warn
      ansible.builtin.copy:
        dest: /etc/systemd/system/zfs-import-scan.service.d/override.conf
        content: |
          [Service]
          SuccessExitStatus=1
      register: zfs_error_as_warn_conf

    - name: reload daemon
      ansible.builtin.systemd:
        daemon_reload: true
      when: zfs_error_as_warn_conf.changed

    - name: restart scan service
      ansible.builtin.systemd:
        name: zfs-import-scan.service
        state: restarted
      when: zfs_error_as_warn_conf.changed

    # wake on lan
    - name: Add post-up ethtool wol enable if defined
      blockinfile:
        path: /etc/network/interfaces
        marker: "        # {mark} WOL BLOCK {{ wol.iface }}"
        insertafter: "^iface {{ wol.bridge }} inet static"
        block: |
          {% filter indent(width=8, first=true) %}
          post-up /usr/sbin/ethtool -s {{ wol.iface }} wol g
          {% endfilter %}
      when: wol is defined

    - name: Apply wol now
      shell: "ethtool -s {{ wol.iface }} wol g"
      when: wol is defined
    
    - name: Disable network offloading features
      blockinfile:
        path: /etc/network/interfaces
        marker: "        # {mark} FIX BLOCK {{ item.iface }}"
        insertafter: "^iface {{ item.bridge }} inet static"
        block: |
          {% filter indent(width=8, first=true) %}
          post-up ethtool -K {{ item.iface }} {% for feature in item.disable_features %}{{ feature }} off {% endfor %}
          {% endfilter %}
      when: net_offloading_fixxes is defined
      loop: "{{ net_offloading_fixxes }}"

    - name: Apply network offloading fix now
      shell: "ethtool -K {{ item.iface }} {% for feature in item.disable_features %}{{ feature }} off {% endfor %}"
      when: net_offloading_fixxes is defined
      loop: "{{ net_offloading_fixxes }}"

- name: Jump host config
  hosts: jump_hosts:all_pve_hosts
  tasks:
    - name: increase sshd max startups for excessive tunneling
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '(?i)^#?\s*MaxStartups'
        line: 'MaxStartups 100:30:200'
        state: present
      notify: restart-sshd
      # only configure when jump hosts defined
      when: groups['jump_hosts'] | length > 0

  handlers:
    - name: restart-sshd
      ansible.builtin.service:
        name: sshd
        state: restarted

- name: Cluster reps setup
  hosts: pve_cluster_reps
  tasks:
    # this has to be set here instead of the inventory because on first runs we use this very playbook
    # to setup the venv. todo: would probably be cleaner if the inventory plugin did the setup in an async fashion
    - set_fact:
        ansible_python_interpreter: /root/.pxc-venv/bin/python

    # install ssh trusted keys between clusters, needed for rsync
    - name: slurp ssh pub key
      slurp:
        src: /root/.ssh/id_rsa.pub
      register: slurp_pub
    
    - name: install keys from other hosts on host
      lineinfile:
        path: /root/.ssh/authorized_keys
        line: "{{ hostvars[item].slurp_pub.content | b64decode | trim }}"
        state: present
      when: inventory_hostname != item
      loop: "{{ groups['pve_cluster_reps'] }}"

    # create pve cloud secret dirs
    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/pve/cloud/kubespray-kubeadm-cert-keys
        state: directory
        recurse: yes

    - name: Create a directory if it does not exist
      ansible.builtin.file:
        path: /etc/pve/cloud/secrets
        state: directory
        recurse: yes

    # check if automation ssh key exists, create locally and copy if it doesnt
    - name: Check if automation id key exists
      ansible.builtin.stat:
        path: /etc/pve/cloud/automation_id_ed25519
      register: automation_id_key

    - name: Generate pve cloud cluster key (used for automation access)
      ansible.builtin.openssh_keypair:
        path: /root/automation_id_ed25519
        type: ed25519
        comment: "automation@{{ pve_cluster_name }}"
      when: not automation_id_key.stat.exists

    - name: Copy to key proxmox fs, direct writing crashes
      command: cp /root/automation_id_ed25519 /root/automation_id_ed25519.pub /etc/pve/cloud/
      when: not automation_id_key.stat.exists

    # generate bind master key
    - name: install bind9 for tsig-keygen
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - bind9
      when: "'dns' in cluster_vars['pve_unique_cloud_services']"

    - name: generate dns access key
      ansible.builtin.shell: |
        tsig-keygen internal. > /etc/pve/cloud/secrets/internal.key
      args:
        creates: /etc/pve/cloud/secrets/internal.key
      when: "'dns' in cluster_vars['pve_unique_cloud_services']"

    # dhcp certificates, only needed on pve cluster that runs the dhcp
    - name: generate certificates for dhcp
      ansible.builtin.shell: |
        cd /etc/pve/cloud/secrets

        openssl genrsa -out dhcp_CA.key 2048
        openssl req -x509 -new -nodes -key dhcp_CA.key -sha256 -days 36500 -out dhcp_CA.crt -batch

        # generate certs for 2 instances
        openssl genrsa -out main_dhcp.key 2048
        openssl genrsa -out failover_dhcp.key 2048

        openssl req -new -key main_dhcp.key -out main_dhcp.csr -batch
        openssl req -new -key failover_dhcp.key -out failover_dhcp.csr -batch
        
        # openssl 3.0 requires the extfile
        openssl x509 -req -in main_dhcp.csr -CA dhcp_CA.crt -CAkey dhcp_CA.key -CAcreateserial -out main_dhcp.crt -days 36500 -sha256 -extfile <(echo -e "[ v3_ext ]\nauthorityKeyIdentifier=keyid") -extensions v3_ext
        openssl x509 -req -in failover_dhcp.csr -CA dhcp_CA.crt -CAkey dhcp_CA.key -CAcreateserial -out failover_dhcp.crt -days 36500 -sha256 -extfile <(echo -e "[ v3_ext ]\nauthorityKeyIdentifier=keyid") -extensions v3_ext
      args:
        executable: /bin/bash 
        creates: /etc/pve/cloud/secrets/failover_dhcp.crt
      when: "'dhcp' in cluster_vars['pve_unique_cloud_services']"

    # keepalived password for the clusters proxy. generate on every cluster since every cluster might have a proxy
    - name: generate keepalived haproxy passphrase
      ansible.builtin.shell: |
        openssl rand -base64 40 | tr -dc 'a-zA-Z0-9' | head -c 20 > /etc/pve/cloud/secrets/haproxy-keepalived.pass
      args:
        creates: /etc/pve/cloud/secrets/haproxy-keepalived.pass

    # generate patroni db secret => central postgres for state and secrets
    - name: generate patroni passphrase
      ansible.builtin.shell: |
        openssl rand -base64 40 | tr -dc 'a-zA-Z0-9' | head -c 20 > /etc/pve/cloud/secrets/patroni.pass
      args:
        creates: /etc/pve/cloud/secrets/patroni.pass
      when: "'psql-state' in cluster_vars['pve_unique_cloud_services']"

    - name: generate letsencrypt account private key
      ansible.builtin.shell: |
        openssl genrsa -out /etc/pve/cloud/secrets/acme-account.key 4096
      args:
        creates: /etc/pve/cloud/secrets/acme-account.key
      run_once: true # will get rsynced to all pves

    # set pve cluster vars
    - name: Copy pve cluster vars
      copy:
        content: "{{ cluster_vars | to_nice_yaml }}"
        dest: /opt/cluster_vars.yaml
    
    - name: Copy to proxmox fs, direct writing crashes
      command: cp /opt/cluster_vars.yaml /etc/pve/cloud/cluster_vars.yaml

    - name: Enable ceph metrics
      command: ceph mgr module enable prometheus
      ignore_errors: true # should be replaced by a check that sees if ceph is configured

    - include_role:
        name: slurp_cluster_secrets

- name: rsync cluster reps
  hosts: pve_cluster_reps
  tags:
    - rsync
  serial: 1
  tasks:
    - set_fact:
        ansible_python_interpreter: /root/.pxc-venv/bin/python

    - name: rsync missing secrets
      ansible.builtin.command: "rsync -avz --inplace --ignore-existing -e 'ssh -o StrictHostKeyChecking=no' root@{{ hostvars[item]['ansible_default_ipv4']['address'] }}:/etc/pve/cloud/secrets/ /etc/pve/cloud/secrets/"
      loop: "{{ groups['pve_cluster_reps'] }}"
      when: inventory_hostname != item
      register: rsync_out

    - debug:
        msg: "{{ item.stdout_lines }}"
      loop: "{{ rsync_out.results }}"
      when: item.stdout_lines is defined

# this fires only conditionally if the cluster has a monitoring stack configured
- name: Vector Log setup
  hosts: all_pve_hosts
  tasks:
    - set_fact:
        ansible_python_interpreter: /root/.pxc-venv/bin/python
    # slurp patroni password
    - name: Slurp file if it exists
      slurp:
        src: /etc/pve/cloud/secrets/patroni.pass
      register: patroni_pass
      run_once: true
    
    # set vars for vector_journald_exporter role
    - set_fact:
        postgres_password: "{{ patroni_pass.content | b64decode | trim }}"
    
    - set_fact:
        pg_conn_str: "postgresql+psycopg2://postgres:{{ postgres_password }}@{{ cluster_vars['pve_haproxy_floating_ip_internal'] }}:5000/pve_cloud?sslmode=disable"
        pve_haproxy_floating_ip_internal: "{{ cluster_vars['pve_haproxy_floating_ip_internal'] }}"

    # journald vector log piping
    - name: check if postgres is available
      community.postgresql.postgresql_ping:
        host: "{{ pve_haproxy_floating_ip_internal }}"
        port: 5000
        login_db: postgres
        login_user: postgres
        login_password: "{{ postgres_password }}" 
      register: postgres_connection_check
      ignore_errors: yes

    - name: run albemic migrations
      alchemy_migrate:
        pg_conn_str: "{{ pg_conn_str }}"
      when: postgres_connection_check.is_available
      run_once: true

    - name: install vector journald exporter
      include_role:
        name: vector_journald_exporter
      vars:
        target_pve: "{{ pve_cluster_name }}.{{ pve_cloud_domain }}"
        stack_name: "{{ inventory_hostname }}" # contains the cluster name
        vlogs_etc_hosts_ip: "{{ cluster_vars['pve_haproxy_floating_ip_internal'] }}" # hosts dont use cloud dns
      when: postgres_connection_check.is_available

# todo: document that for the initial setup playbooks need to be run twice because of state

# this is mainly needed for multi cloud functionality (multi cloud gateway api is using these secrets)
- name: sync secrets into postgres
  hosts: pve_cluster_reps
  tasks:
    - set_fact:
        ansible_python_interpreter: /root/.pxc-venv/bin/python
    # slurp patroni password
    - name: Slurp file if it exists
      slurp:
        src: /etc/pve/cloud/secrets/patroni.pass
      register: patroni_pass
    
    - set_fact:
        postgres_password: "{{ patroni_pass.content | b64decode | trim }}"
    
    - set_fact:
        pg_conn_str: "postgresql+psycopg2://postgres:{{ postgres_password }}@{{ cluster_vars['pve_haproxy_floating_ip_internal'] }}:5000/pve_cloud?sslmode=disable"
    
    - name: check if postgres is available
      community.postgresql.postgresql_ping:
        host: "{{ cluster_vars['pve_haproxy_floating_ip_internal'] }}"
        port: 5000
        login_db: postgres
        login_user: postgres
        login_password: "{{ postgres_password }}"
      register: postgres_connection_check
      ignore_errors: yes

    - name: run albemic migrations
      alchemy_migrate:
        pg_conn_str: "{{ pg_conn_str }}"
      when: postgres_connection_check.is_available
      run_once: true

    - slurp_cloud_secrets_async:
      register: slurped_secrets
      when: postgres_connection_check.is_available

    - name: create secret map
      set_fact:
        secret_map: "{{ secret_map | default({}) | combine({item.path | basename: item.content}) }}"
      loop: "{{ slurped_secrets.results }}"    
      loop_control:
        label: "hidden"
      when: postgres_connection_check.is_available

    - name: write cluster vars
      alchemy_upsert:
        pg_conn_str: "{{ pg_conn_str }}"
        table: px_cloud_secrets
        values:
          cloud_domain: "{{ pve_cloud_domain }}"
          secret_name: "{{ pve_cluster_name }}-cluster-vars"
          secret_data: "{{ cluster_vars }}"
          secret_type: "cluster-vars"
        conflict_cols:
          - secret_name
          - cloud_domain
      when: postgres_connection_check.is_available

    - name: write cluster secrets
      alchemy_upsert:
        pg_conn_str: "{{ pg_conn_str }}"
        table: px_cloud_secrets
        values:
          cloud_domain: "{{ pve_cloud_domain }}"
          secret_name: "{{ pve_cluster_name }}-cluster-secrets"
          secret_data: "{{ secret_map }}"
          secret_type: "cluster-secrets"
        conflict_cols:
          - secret_name
          - cloud_domain
      when: postgres_connection_check.is_available
