- name: Setup node running ansible (local machine)
  hosts: localhost
  tasks:
    - set_fact:
        pip_extra_args: >-
          {% if test_repos_ip is defined %}
          --index-url http://{{ test_repos_ip }}:8088/simple --trusted-host {{ test_repos_ip }}
          {% else %}
          ""
          {% endif %}
    
    - debug:
        var: pip_extra_args
      
    - name: Install pve cloud collection requirements
      ansible.builtin.pip:
        requirements: "{{ playbook_dir | dirname }}/meta/ee-requirements.txt"
        extra_args: "{{ pip_extra_args }}"

    - name: install packages for caching
      become: true
      apt:
        update_cache: yes
        pkg:
          - nfs-common
          - rsync

    # todo: apt install avahi? / other reqs
